<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MatlevSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Matikan Foreign Key Constraint & Bersihkan Data Lama
        Schema::disableForeignKeyConstraints();
        DB::table('maturity_levels')->truncate();
        DB::table('sub_criterias')->truncate();
        DB::table('criterias')->truncate();
        Schema::enableForeignKeyConstraints();

        $now = now();

        // 2. Isi Data Kriteria (tabel criterias)
        DB::table('criterias')->insert([
            ['id' => 1, 'code' => 'K-01', 'title' => 'Leadership & Management Commitment', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'code' => 'K-02', 'title' => 'Audit, Assessment and Inspection', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'code' => 'K-03', 'title' => 'Penerapan Identifikasi Bahaya, Penilaian dan Pengendalian Risiko (IBPPR)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'code' => 'K-04', 'title' => 'Safety Training and Education', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'code' => 'K-05', 'title' => 'Safety Campaign and Communication', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'code' => 'K-06', 'title' => 'Reporting', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // 3. Isi Data Sub Kriteria (tabel sub_criterias)
        DB::table('sub_criterias')->insert([
            ['id' => 1, 'criteria_id' => 1, 'code' => '1.1', 'title' => 'Menyusun RKAP Bidang K3 berdasarkan kajian IBPPR terhadap aktifitas operasional unit', 'description' => 'Program kerja dan Anggaran bidang K3 di Unit Induk dan Unit Pelaksana tertuang dalam RKAP', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'criteria_id' => 1, 'code' => '1.2', 'title' => 'Menerapan Contractor Safety Management System (CSMS)', 'description' => 'Proses pengadaan barang dan jasa telah menerapkan seluruh tahapan CSMS', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'criteria_id' => 1, 'code' => '1.3', 'title' => 'Membangun Sistem Manajemen K3 Terintegrasi', 'description' => 'Pengelolaan K3 telah menerapkan Sistem Manajemen K3 Terintegrasi', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'criteria_id' => 2, 'code' => '2.1', 'title' => 'Melakukan Inspeksi K3 Manajemen', 'description' => 'Pelaksanaan Inspeksi K3 Manajemen', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'criteria_id' => 2, 'code' => '2.2', 'title' => 'Melakukan Audit Internal SMK3', 'description' => 'Pelaksanaan Audit Internal SMK3 PP 50/2012', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'criteria_id' => 2, 'code' => '2.3', 'title' => 'Melakukan Audit K3 pada Mitra Kerja', 'description' => 'Pelaksanaan Audit K3 Mitra Kerja', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'criteria_id' => 2, 'code' => '2.4', 'title' => 'Melakukan Pengukuran Lingkungan Kerja', 'description' => 'Pengukuran Lingkungan Kerja di Tempat Kerja', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'criteria_id' => 2, 'code' => '2.5', 'title' => 'Melakukan Pemeriksaan Kesehatan Pegawai', 'description' => 'Pemeriksaan Kesehatan bagi pegawai diatas 40 tahun dan pekerja pada resiko tinggi.', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'criteria_id' => 2, 'code' => '2.6', 'title' => 'Melakukan Pengukuran Hygiene Factor Mitra Kerja', 'description' => 'Pelaksanaan Pengukuran Hygiene Factor kepada Mitra Kerja', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'criteria_id' => 3, 'code' => '3.1', 'title' => 'Menerapkan Ijin Kerja (WP) pada setiap pekerjaan yang memiliki tingkat risiko sesuai hasil Risk Assessment Pekerjaan', 'description' => 'Penerapan Ijin Kerja (WP) setiap pekerjaan yang berpotensi bahaya / kecelakaan kerja', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'criteria_id' => 3, 'code' => '3.2', 'title' => 'Menyediakan Sistem Proteksi Kebakaran Instalasi Ketenagalistrikan sesuai IBPPR', 'description' => 'Sistem Proteksi Kebakaran mampu memproteksi Aset Properti dan Instalasi Ketenagalistrikan', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'criteria_id' => 3, 'code' => '3.3', 'title' => 'Melaksanakan Simulasi Peralatan Proteksi Kebakaran dan Simulasi Tanggap Darurat', 'description' => 'Pelaksanaan simulasi peralatan proteksi kebakaran dan simulasi tanggap darurat', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'criteria_id' => 4, 'code' => '4.1', 'title' => 'Melaksanakan Pelatihan K3 Manajemen', 'description' => 'Pelaksanaan Pelatihan K3 Manajemen', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 14, 'criteria_id' => 4, 'code' => '4.2', 'title' => 'Melakukan Edukasi K3 Internal (Pegawai dan Karyawan Mitra Kerja)', 'description' => 'Pelaksanaan Edukasi K3 Internal', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 15, 'criteria_id' => 5, 'code' => '5.1', 'title' => 'Melaksanakan Rapat P2K3', 'description' => 'Pelaksanaan Rapat P2K3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'criteria_id' => 5, 'code' => '5.2', 'title' => 'Melakukan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum dan dampak aktifitas ketenagalistrikan terhadap masyarakat', 'description' => 'Pelaksanaan edukasi dan sosialisasi bahaya listrik kepada Masyarakat Umum', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'criteria_id' => 6, 'code' => '6.1', 'title' => 'Melaksanakan pelaporan pada Aplikasi Inspekta', 'description' => 'Pelaporan pada Aplikasi INSPEKTA', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // 4. Isi Data Indikator Level (tabel maturity_levels)
        DB::table('maturity_levels')->insert([
            // Sub Criteria 1.1 (ID: 1)
            ['sub_criteria_id' => 1, 'level' => 1, 'description' => "Belum terdapat kebijakan/ komitmen manajemen untuk penerapan K3 secara keseluruhan.\nUnit telah menyusun IBPPR dan belum terdapat ketersediaan anggaran pengelolaan K3.", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 1, 'level' => 2, 'description' => "Sudah memiliki kebijakan/ komitmen manajemen untuk penerapan K3, Identifikasi potensi bahaya hanya bersifat dokumen dan tidak diturunkan dalam sebuah program K3. sehingga penyediaan anggaran hanya sebatas adanya anggaran tetapi tidak efektif untuk komitmen penurunan risiko pekerjaan.", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 1, 'level' => 3, 'description' => "Sudah memiliki kebijakan/ komitmen K3 dan juga menerbitkan kebijakan khusus K3 penunjang operasional, Identifikasi potensi bahaya sudah menyeluruh untuk semua aktifitas dan menurunkan sebuah program K3 yang berkaitan dengan mitigasi risiko, dan diterjemahkan dalam sebuah rencana anggaran operasional K3 berdasarkan program K3 yang merupakan sekumpulan program mitigasi risiko kerja di IBPPR", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 1, 'level' => 4, 'description' => "Sudah memiliki kebijakan/ komitmen K3 dan juga menerbitkan kebijakan khusus K3 penunjang operasional, Identifikasi potensi bahaya sudah menyeluruh untuk semua aktifitas dan menurunkan sebuah program K3 yang berkaitan dengan mitigasi risiko dan diinformasikan ke seluruh level pekerja unit, dan diterjemahkan dalam sebuah rencana anggaran operasional K3 berdasarkan program K3 yang merupakan sekumpulan program mitigasi risiko kerja di IBPPR dan dipastikan konsistensi pengelolaan K3 dilihat dari realisasi anggaran k3", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 1, 'level' => 5, 'description' => "Komitmen/ kebijakan K3 sudah menjadi kebutuhan dan menjadi bagian yang tidak terpisahkan dalam operasional unit, program k3 disusun secara terstruktur berdasarkan kajian IBPPR yang rutin direview secara berkala dan komitmen manajemen tentang kepastian dan ketersediaan anggaran pembiayaan K3 sesuai dengan perencanaan yang terlah disiapkan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 1.2 (ID: 2)
            ['sub_criteria_id' => 2, 'level' => 1, 'description' => "belum menerapkan klausul CSMS dalam pelaksanaan Pengadaan barang/jasa sehingga persyaratan Risk Assessment seluruh Pekerjaan yang akan ditenderkan belum menjadi dokumen mandatory persyaratan sebuah pengadaan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 2, 'level' => 2, 'description' => "Melakukan Risk Assessment seluruh Pekerjaan yang akan ditenderkan dan menjadi dokumen mandatory untuk proses pengadaan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 2, 'level' => 3, 'description' => "Melaksanakan CSMS Full cycle terhadap pekerjaan yang wajib melakukan full cycle ( minimal risiko tinggi), dengan memonitoring jumlah pekerjaan yang dilakukan vendor/kontraktor/mitra kerja yang berisiko minimal tinggi sesuai dengan kontrak kerja pengadaan yang terbit + jumlah penerapan full cycle ( berdasarkan jumlah pelaksanaan sampai tahap WIP dan Final Evaluation setiap tahunnya) + target pelaksanaan < 90% jumlah pekerjaan yang wajib di full cycle telah dilakukan CSMS Full cycle minimal sampai tahap WIP", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 2, 'level' => 4, 'description' => "Melaksanakan CSMS Full cycle terhadap pekerjaan yang wajib melakukan full cycle ( minimal risiko tinggi), dengan memonitoring jumlah pekerjaan yang dilakukan vendor/kontraktor/mitra kerja yang berisiko minimal tinggi sesuai dengan kontrak kerja pengadaan yang terbit + jumlah penerapan full cycle ( berdasarkan jumlah pelaksanaan sampai tahap WIP dan Final Evaluation setiap tahunnya) + target pelaksanaan ≥ 90% jumlah pekerjaan yang wajib di full cycle telah dilakukan CSMS Full cycle minimal sampai tahap WIP", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 2, 'level' => 5, 'description' => "90% Kontraktor / Vendor / Mitra Kerja di Unit Induk dan Unit Pelaksana telah bersertifikat CSMS.\n100% jumlah pekerjaan yang wajib di full cycle telah dilakukan CSMS Full cycle minimal sampai tahap WIP\nMelakukan evaluasi pelaksanaan CSMS, tindak lanjut dan rekomendasi perbaikan kepada Kontraktor", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 1.3 (ID: 3)
            ['sub_criteria_id' => 3, 'level' => 1, 'description' => "Belum membangun Sistem Manajemen SNI ISO 45001 : 2018 di Unit Induk", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 3, 'level' => 2, 'description' => "Unit Induk telah membangun Sistem Manajemen SNI ISO 45001:2018 yang terintegrasi dengan SMK3 PP 50/2012 dan menyusun prosedur-prosedurnya, namun integrasinya belum meliputi seluruh Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 3, 'level' => 3, 'description' => "Unit Induk telah membangun Sistem Manajemen Terintegrasi ISO 45001:2018 dengan SMK3 PP 50/2012 dan menyusun prosedur-prosedurnya serta dokumen integrasinya telah meliputi seluruh Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 3, 'level' => 4, 'description' => "Unit Induk telah membangun Sistem Manajemen Terintegrasi ISO 45001:2018 dengan SMK3 PP 50/2012 dan seluruh Unit telah dilakukan Sertifikasi", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 3, 'level' => 5, 'description' => "Unit Induk telah membangun Sistem Manajemen Terintegrasi ISO 45001:2018 dengan SMK3 PP 50/2012 dan seluruh Unit telah dilakukan Sertifikasi serta memiliki monitoring tindaklanjut temuan audit internal maupun audit eksternal", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.1 (ID: 4)
            ['sub_criteria_id' => 4, 'level' => 1, 'description' => "Terjadi kecelakaan kerja (Luka Berat, Luka Berat Cacat dan Fatality) inspeksi K3 pada lokasi dan aktifitas pekerjaan terkait tidak efektif dalam mengendalikan risiko.", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 4, 'level' => 2, 'description' => "Memiliki rencana inspeksi K3 General Manager dan Manajer Unit Pelaksana selama 6 bulan atau 1 tahun\nGeneral Manager & Manajer Unit Pelaksana melaksanakan inspeksi K3 sesuai target jumlah dan waktu (1 bulan sekali)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 4, 'level' => 3, 'description' => "Memiliki rencana inspeksi K3 General Manager dan Manajer Unit Pelaksana selama 6 bulan atau 1 tahun\nGeneral Manager & Manajer Unit Pelaksana melaksanakan inspeksi K3 sesuai target jumlah dan waktu (1 bulan sekali) serta memberikan catatan temuan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 4, 'level' => 4, 'description' => "General Manager, Manajer Unit Pelaksana & Manajer Unit Layanan melaksanakan inspeksi K3 1 kali setiap bulan dan temuannya dilaporkan melalui Aplikasi K3 Korporat (Inspekta)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 4, 'level' => 5, 'description' => "General Manager, Senior Manager, Manajer Unit Pelaksana, MSB Teknis, Manajer Bagian Teknis & Manajer Unit Layanan melaksanakan inspeksi K3 1 kali setiap bulan dan temuannya dilaporkan melalui Aplikasi K3 Korporat (Inspekta)\nMemiliki monitoring temuan inspeksi K3 Manajemen di aplikasi Inspekta dan monitoring tindak lanjutnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.2 (ID: 5)
            ['sub_criteria_id' => 5, 'level' => 1, 'description' => "Belum melaksanakan Audit Internal SMK3 atau Pelaksanaan Audit Internal hanya dilaksanakan di Unit Induk namun tidak sesuai dengan target waktu (min 1 tahun sekali)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 5, 'level' => 2, 'description' => "Memiliki rencana/jadwal Audit Internal Unit Induk dan Unit Pelaksana.\nPelaksanaan Audit Internal dilaksanakan di Unit Induk dan sebagian Unit Pelaksana namun tidak sesuai dengan target waktu (min 1 tahun sekali)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 5, 'level' => 3, 'description' => "Pelaksanaan Audit Internal dilaksanakan di Unit Induk dan seluruh Unit Pelaksana sesuai dengan target waktu (min 1 tahun sekali), memiliki jadwal tindak lanjut dari temuan ketidaksesuaian dan penanggung jawab tindak lanjutnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 5, 'level' => 4, 'description' => "Memiliki jadwal tindak lanjut dari temuan ketidaksesuaian Audit Internal dan penanggung jawab tindak lanjutnya serta realisasi tindak lanjut temuan ketidaksesuaian Audit Internal telah mencapai 100%", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 5, 'level' => 5, 'description' => "Realisasi tindak lanjut temuan ketidaksesuaian mencapai 100%, dan tidak terdapat temuan Major.\nTelah melakukan Tinjauan Manajemen SMK3 serta OFI dan AFI berdasarkan hasil Audit Internal", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.3 (ID: 6)
            ['sub_criteria_id' => 6, 'level' => 1, 'description' => "Belum melaksanakan Audit K3 Mitra Kerja atau Audit K3 mitra kerja hanya dilakukan pada mitra kerja di Unit Induk", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 6, 'level' => 2, 'description' => "Audit K3 mitra kerja hanya dilakukan pada mitra kerja di Unit Induk dan sebagian mitra kerja Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 6, 'level' => 3, 'description' => "Audit K3 mitra kerja dilakukan pada mitra kerja di Unit Induk dan seluruh mitra kerja di Unit Pelaksana serta memiliki rekomendasi perbaikan dari temuan ketidaksesuaian dan penanggung jawabnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 6, 'level' => 4, 'description' => "Audit K3 mitra kerja dilakukan pada mitra kerja di Unit Induk dan seluruh mitra kerja di Unit Pelaksana serta memiliki monitoring realisasi tindak lanjut atau rekomendasi perbaikan dari temuan ketidaksesuaian dan monitoring realisasi tindak lanjut telah mencapai 100% tidaksesuaian", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 6, 'level' => 5, 'description' => "Audit K3 mitra kerja dilakukan pada mitra kerja di Unit Induk dan seluruh mitra kerja di Unit Pelaksana serta memiliki monitoring realisasi tindak lanjut atau rekomendasi perbaikan dari temuan ketidaksesuaian dan monitoring realisasi tindak lanjut telah mencapai 100% serta OFI dan AFI berdasarkan temuan audit", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.4 (ID: 7)
            ['sub_criteria_id' => 7, 'level' => 1, 'description' => "Belum melaksanakan pengukuran lingkungan kerja atau pengukuran lingkungan kerja hanya dilakukan di sebagian Unit", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 7, 'level' => 2, 'description' => "Pengukuran lingkungan kerja hanya dilakukan di Unit Induk dan sebagian Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 7, 'level' => 3, 'description' => "Pengukuran lingkungan kerja dilakukan di Unit Induk dan seluruh Unit Pelaksana serta memiliki monitoring tindak lanjut temuan ketidaksesuaian dan penanggung jawab tindak lanjutnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 7, 'level' => 4, 'description' => "Pengukuran lingkungan kerja dilakukan di Unit Induk dan seluruh Unit Pelaksana serta memiliki monitoring tindak lanjut temuan ketidaksesuaian dan penanggung jawab tindak lanjutnya serta monitoring realisasi tindak lanjut temuan ketidaksesuaian\nPelaksana pengukuran lingkungan kerja memiliki sertifikat kompetensi", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 7, 'level' => 5, 'description' => "Pengukuran lingkungan kerja dilakukan di Unit Induk dan seluruh Unit Pelaksana serta memiliki monitoring tindak lanjut temuan ketidaksesuaian dan penanggung jawab tindak lanjutnya serta monitoring realisasi tindak lanjut temuan ketidaksesuaian\nPelaksana pengukuran lingkungan kerja memiliki sertifikat kompetensi\nMemiliki OFI & AFI berdasarkan temuan ketidaksesuaian", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.5 (ID: 8)
            ['sub_criteria_id' => 8, 'level' => 1, 'description' => "Belum melaksanakan pemeriksaan kesehatan sesuai ketentuan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 8, 'level' => 2, 'description' => "Pemeriksaan kesehatan dilaksanakan hanya di Unit Induk dan sebagian Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 8, 'level' => 3, 'description' => "Pemeriksaan kesehatan dilaksanakan di Unit Induk dan seluruh Unit Pelaksana serta memiliki jadwal dan pelaksanaan sosialisasi hasil pemeriksaan kesehatan serta memiliki rekap 10 penyakit dominan dan rencana pencegahan Penyakit Akibat Kerja (PAK)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 8, 'level' => 4, 'description' => "Pemeriksaan kesehatan dilaksanakan di Unit Induk dan seluruh Unit Pelaksana serta memiliki jadwal dan pelaksanaan sosialisasi hasil pemeriksaan kesehatan serta memiliki rekap 10 penyakit dominan dan rencana pencegahan Penyakit Akibat Kerja (PAK) serta monitoring realisasi pencegahan PAK", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 8, 'level' => 5, 'description' => "Pemeriksaan kesehatan dilaksanakan di Unit Induk dan seluruh Unit Pelaksana serta memiliki jadwal dan pelaksanaan sosialisasi hasil pemeriksaan kesehatan serta memiliki rekap 10 penyakit dominan dan rencana pencegahan Penyakit Akibat Kerja (PAK) serta monitoring realisasinya dan rekomendasi mutasi atau pemindahan tempat kerja Pegawai yang terjangkit PAK", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 2.6 (ID: 9)
            ['sub_criteria_id' => 9, 'level' => 1, 'description' => "Belum melaksanakan pengukuran Hygiene Factor Mitra Kerja (TAD)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 9, 'level' => 2, 'description' => "Pengukuran Hygiene Factor Mitra Kerja dilaksanakan hanya di Unit Induk dan sebagian Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 9, 'level' => 3, 'description' => "Pengukuran Hygiene Factor Mitra Kerja dilaksanakan di Unit Induk dan seluruh Unit Pelaksana serta memiliki monitoring tindak lanjut dari temuan ketidaksesuaian dan penanggung jawabnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 9, 'level' => 4, 'description' => "Pengukuran Hygiene Factor Mitra Kerja dilaksanakan di Unit Induk dan seluruh Unit Pelaksana dengan jumlah peserta mencapai 60% dari jumlah personil Mitra Kerja serta memiliki monitoring tindak lanjut dari temuan ketidaksesuaian dan penanggung jawabnya serta monitoring realisasi tindak lanjut temuan ketidaksesuaianuaian", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 9, 'level' => 5, 'description' => "Pengukuran Hygiene Factor Mitra Kerja dilaksanakan di Unit Induk dan seluruh Unit Pelaksana dengan jumlah peserta mencapai 80% dari jumlah personil Mitra Kerja serta memiliki monitoring tindak lanjut dari temuan ketidaksesuaian dan penanggung jawabnya serta monitoring realisasi tindak lanjut temuan ketidaksesuaian dan OFI AFI berdasarkan temuan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 3.1 (ID: 10)
            ['sub_criteria_id' => 10, 'level' => 1, 'description' => "Apabila terjadi kecelakaan kerja (Luka Berat, Luka Berat Cacat dan Fatality).\nTidak efektif dalam penerapan identifikasi bahaya, penilaian dan pengendalian risiko", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 10, 'level' => 2, 'description' => "Menerapkan Ijin Kerja (WP) pada setiap pekerjaan yang memiliki tingkat risiko moderat, tinggi, sangat tinggi dan ekstrem, yang dilengkapi / dilampiri JSA, IBPPR, SOP / Instruksi Kerja pada sebagian jenis pekerjaan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 10, 'level' => 3, 'description' => "Menerapkan Ijin Kerja (WP) pada setiap pekerjaan yang memiliki tingkat risiko moderat, tinggi, sangat tinggi dan ekstrem, yang dilengkapi / dilampiri JSA, IBPPR, SOP / Instruksi Kerja serta ada pengawas pekerjaan dan pengawas K3 pada seluruh jenis pekerjaan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 10, 'level' => 4, 'description' => "Menerapkan Ijin Kerja (WP) pada setiap pekerjaan yang memiliki tingkat risiko moderat, tinggi, sangat tinggi dan ekstrem, yang dilengkapi / dilampiri JSA, IBPPR, SOP / Instruksi Kerja serta ada pengawas pekerjaan dan pengawas K3 yang kompeten pada seluruh jenis pekerjaan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 10, 'level' => 5, 'description' => "Menerapkan Ijin Kerja (WP) pada setiap pekerjaan yang memiliki tingkat risiko moderat, tinggi, sangat tinggi dan ekstrem, yang dilengkapi / dilampiri JSA, IBPPR, SOP / Instruksi Kerja serta ada pengawas pekerjaan dan pengawas K3 yang kompeten pada seluruh jenis pekerjaan.\nMelakukan review SOP/IK, IBPPR dan JSA minimal 1 kali dalam setahun", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 3.2 (ID: 11)
            ['sub_criteria_id' => 11, 'level' => 1, 'description' => "Jika terjadi kecelakaan instalasi (kebakaran) di Unit Induk atau di Unit Pelaksana atau di Sub Unit Pelaksana serta Instalasi Ketenagalistrikan yang merupakan aset dari Unit", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 11, 'level' => 2, 'description' => "Identifikasi Bahaya, Penilaian dan Pengendalian Resiko (IBPPR) yang mengindentifikasi potensi bahaya kebakaran dari aktifitas rutin/non rutin aktifitas operasional unit ( Gudang, GI, Pusat Listrik/Pembangkit Listrik, dll) dan perkantoran di Unit Induk dan sebagian Unit Pelaksana atau Sub Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 11, 'level' => 3, 'description' => "Identifikasi Bahaya, Penilaian dan Pengendalian Resiko (IBPPR) yang mengindentifikasi potensi bahaya kebakaran dari aktifitas rutin/non rutin aktifitas operasional unit ( Gudang, GI, Pusat Listrik/Pembangkit Listrik, dll) serta perkantoran dan menyusun program mitigasi sampai proses penyediaanya dalam upaya penurunan risiko bahaya kebakaran sesuai standar yang telah ditetapkan ( SPLN Sistem Proteksi Kebakaran/ standar lain) di Unit Induk dan seluruh Unit Pelaksana serta Sub Unit Pelaksana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 11, 'level' => 4, 'description' => "Identifikasi Bahaya, Penilaian dan Pengendalian Resiko (IBPPR) yang mengindentifikasi potensi bahaya kebakaran dari aktifitas rutin/non rutin aktifitas operasional unit ( Gudang, GI, Pusat Listrik/Pembangkit Listrik, dll) serta perkantoran dan menyusun program mitigasi sampai proses penyediaanya dalam upaya penurunan risiko bahaya kebakaran sesuai standar yang telah ditetapkan ( SPLN Sistem Proteksi Kebakaran/ standar lain) dan memiliki monitoring rencana dan realisasi penyediaan proteksi kebakaran", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 11, 'level' => 5, 'description' => "Identifikasi Bahaya, Penilaian dan Pengendalian Resiko (IBPPR) Instalasi Ketenagalistrikan (Gedung Kantor, Gudang, GI, Pusat Listrik/Pembangkit Listrik) telah mencakup kebutuhan penyediaan proteksi kebakaran di Unit Induk dan seluruh Unit Pelaksana serta Sub Unit Pelaksana dan realisasi penyediaan proteksi kebakaran telah mencapai 100% serta memiliki OFI dan AFI dalam evaluasi pengendalian risiko kebakaran", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 3.3 (ID: 12)
            ['sub_criteria_id' => 12, 'level' => 1, 'description' => "Tidak melaksanakan simulasi Tanggap darurat atau hanya melaksanakan penggunaan peralatan proteksi kebakaran atau hanya melaksanakan simulasi tanggap darurat di Unit Induk", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 12, 'level' => 2, 'description' => "Unit telah menyusun IBPPR terkait potensi bahaya kondisi darurat dan mitigasi bencana alam dan penyusunan panduan penanganan kondisi darurat dan kesiapan sarana prasarana", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 12, 'level' => 3, 'description' => "1. Unit telah menyusun IBPPR terkait potensi bahaya kondisi darurat dan mitigasi bencana alam dan penyusunan panduan penanganan kondisi darurat dan kesiapan sarana prasarana.\n2. Mensimulasikan prosedur tanggap darurat dan tanggap bencana dengan melakukan evaluasi pelaksanaan simulasi minimal 1 tahun", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 12, 'level' => 4, 'description' => "1. Unit telah menyusun IBPPR terkait potensi bahaya kondisi darurat dan mitigasi bencana alam dan penyusunan panduan penanganan kondisi darurat dan kesiapan sarana prasarana.\n2. Mensimulasikan prosedur tanggap darurat dan tanggap bencana dengan melakukan evaluasi pelaksanaan simulasi lebih dari 1 kali dalam setahun \n3. monitoring kesiapan peralatan tanggap bencana dan kompetensi personel tim tanggap darurat", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 12, 'level' => 5, 'description' => "1. Unit telah menyusun IBPPR terkait potensi bahaya kondisi darurat dan mitigasi bencana alam dan penyusunan panduan penanganan kondisi darurat dan kesiapan sarana prasarana.\n2. Mensimulasikan prosedur tanggap darurat dan tanggap bencana dengan melakukan evaluasi pelaksanaan simulasi lebih dari 1 kali dalam setahun \n3. monitoring kesiapan peralatan tanggap bencana dan kompetensi personel tim tanggap darurat\n4. melaksanakan pelatihan terkait BCP untuk para tim tanggap darurat\n5. simulasi tanggap darurat bekerjasama dengan pihak eksternal", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 4.1 (ID: 13)
            ['sub_criteria_id' => 13, 'level' => 1, 'description' => "Memiliki rencana pelatihan K3 Manajemen Unit Induk dan Manajemen Unit Pelaksana, namun belum dilaksanakan sesuai ketentuan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 13, 'level' => 2, 'description' => "Memiliki rencana pelatihan K3 Manajemen Unit Induk dan Manajemen Unit Pelaksana dan pelatihan dilaksanakan sesuai ketentuan, namun tidak seluruh Manajemen Unit Induk dan Unit Pelaksana mengikuti pelatihan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 13, 'level' => 3, 'description' => "Memiliki rencana pelatihan K3 Manajemen Unit Induk dan Manajemen Unit Pelaksana dan pelatihan dilaksanakan sesuai ketentuan serta seluruh Manajemen Unit Induk dan Unit Pelaksana mengikuti pelatihan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 13, 'level' => 4, 'description' => "Memiliki rencana pelatihan K3 Manajemen Unit Induk dan Manajemen Unit Pelaksana dan pelatihan dilaksanakan sesuai ketentuan serta seluruh Manajemen Unit Induk dan Unit Pelaksana mengikuti pelatihan.\nMelakukan evaluasi pelaksanaan pelatihan K3 bagi Manajemen", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 13, 'level' => 5, 'description' => "Jumlah pelaksanaan pelatihan K3 Manajemen melebihi ketentuan.\nMelakukan Sertifikasi K3 bagi Manajemen Unit Induk dan/atau Unit Pelaksana dari BNSP atau Kemenaker", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 4.2 (ID: 14)
            ['sub_criteria_id' => 14, 'level' => 1, 'description' => "Unit Induk dan Unit Pelaksana tidak melaksanakan Edukasi K3 kepada pegawai dan karyawan mitra kerja atau Terjadi kecelakaan kerja pegawai atau karyawan mitra kerja (Luka Berat, Luka Berat Cacat dan Fatality) pelaksanaan edukasi K3 kepada pegawai atau karyawan mitra kerja tidak efektif", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 14, 'level' => 2, 'description' => "Unit Induk dan sebagian Unit Pelaksana melaksanakan Edukasi K3 kepada pegawai dan karyawan mitra kerja", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 14, 'level' => 3, 'description' => "Unit Induk dan seluruh Unit Pelaksana melaksanakan Edukasi K3 kepada pegawai dan karyawan mitra kerja, namun tidak semua pegawai dan karyawan mitra kerja mengikuti edukasi K3", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 14, 'level' => 4, 'description' => "Unit Induk dan seluruh Unit Pelaksana melaksanakan Edukasi K3 kepada pegawai dan karyawan mitra kerja dan diikuti oleh semua pegawai dan karyawan mitra kerja serta melakukan evaluasi pelaksanaan edukasi K3", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 14, 'level' => 5, 'description' => "Unit Induk dan seluruh Unit Pelaksana melaksanakan Edukasi K3 kepada pegawai dan karyawan mitra kerja melebihi dari ketentuan dan diikuti oleh seluruh pegawai dan karyawan mitra kerja.\nSeluruh pelaksana pekerjaan dan pengawas pekerjaan mendapatkan Sertifikasi K3 dari BNSP / Kemenaker / Pusdiklat / Lembaga Sertifikasi Kompetensi lainnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 5.1 (ID: 15)
            ['sub_criteria_id' => 15, 'level' => 1, 'description' => "Unit Induk dan Unit Pelaksana tidak melaksanakan Rapat P2K3 setiap bulan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 15, 'level' => 2, 'description' => "Sebagian Unit melaksanakan Rapat P2K3 dilakukan setiap bulan dan dihadiri oleh Ketua P2K3/ pimpinan unit serta mengirimkan laporan P2K3 ke Disnaker (sesuai ketentuan)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 15, 'level' => 3, 'description' => "Seluruh Unit melaksanakan Rapat P2K3 dilakukan setiap bulan dan dihadiri oleh Ketua P2K3/ pimpinan unit dan perwakilan setiap bidang kerja serta mengirimkan laporan P2K3 ke Disnaker (sesuai ketentuan)", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 15, 'level' => 4, 'description' => "Seluruh Unit melaksanakan Rapat P2K3 dan dihadiri oleh Ketua P2K3/ pimpinan unit dan perwakilan setiap bidang kerja serta mengirimkan laporan P2K3 ke Disnaker (sesuai ketentuan) dan memiliki monitoring tindaklanjut hasil temuan atau pembahasan pada rapat P2K3", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 15, 'level' => 5, 'description' => "Seluruh Unit melaksanakan Rapat P2K3 dan dihadiri oleh Ketua P2K3 serta mengirimkan laporan P2K3 sesuai ketentuan yang berlaku ke Disnaker dan memiliki monitoring tindaklanjut hasil temuan atau pembahasan pada rapat P2K3 serta 100% telah selesai ditindaklanjuti", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 5.2 (ID: 16)
            ['sub_criteria_id' => 16, 'level' => 1, 'description' => "Seluruh Unit tidak melaksanakan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 16, 'level' => 2, 'description' => "Sebagian besar Unit melaksanakan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum hanya dengan menyebarkan flyer / stiker / pamflet / spanduk / x-banner atau melalui media cetak / elektronik.\nAtau sebagian besar Unit melaksanakan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum dengan melakukan kunjungan atau mengadakan pertemuan dengan warga masyarakat umum", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 16, 'level' => 3, 'description' => "Seluruh Unit melaksanakan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum hanya dengan menyebarkan flyer / stiker / pamflet / spanduk / x-banner atau melalui media cetak / elektronik.\nAtau seluruh Unit melaksanakan Edukasi dan Upaya Pencegahan Kecelakaan Masyarakat Umum dengan melakukan kunjungan atau mengadakan pertemuan dengan warga masyarakat umum sesuai jumlah dan waktu yang telah ditentukan sesuai ketentuan serta menyusun hasil pembahasan (notulen) pelaksanaannya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 16, 'level' => 4, 'description' => "1. Seluruh Unit melaksanakan sosialisasi bahaya listrik dengan menyebarkan flyer / stiker / pamflet / spanduk / x-banner atau melalui media cetak / elektronik 1 kali setiap bulan,\natau melakukan kunjungan / pertemuan dengan warga masyarakat umum 1 kali setiap triwulan serta menyusun hasil pembahasan (notulen) pelaksanaannya\ndan sosialisasi bahaya listrik melalui televisi atau radio setempat\n2. melakukan survei pemahaman dan efektifitas pelaksanaan sosialisasi\n3. penurunan jumlah KMU sebesar 25% dari tahun sebelumnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 16, 'level' => 5, 'description' => "1. Seluruh Unit melaksanakan sosialisasi bahaya listrik dengan menyebarkan flyer / stiker / pamflet / spanduk / x-banner atau melalui media cetak / elektronik 1 kali setiap bulan,\natau melakukan kunjungan / pertemuan dengan warga masyarakat umum 1 kali setiap triwulan serta menyusun hasil pembahasan (notulen) pelaksanaannya\ndan sosialisasi bahaya listrik melalui televisi atau radio setempat\n2. melakukan survei pemahaman dan efektifitas pelaksanaan sosialisasi\n3. penurunan jumlah KMU sebesar 50% dari tahun sebelumnya", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],

            // Sub Criteria 6.1 (ID: 17)
            ['sub_criteria_id' => 17, 'level' => 1, 'description' => "Unit tidak melakukan pelaporan Unsafe Act, Unsafe Condition, Nearmiss dan Accident melalui Aplikasi Inspekta", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 17, 'level' => 2, 'description' => "Sebagian besar Unit Induk dan Unit Pelaksana tidak melakukan pelaporan Unsafe Act, Unsafe Condition, Nearmiss dan Accident melalui Aplikasi Inspekta dan belum menetapkan User sesuai dengan ketentuan", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 17, 'level' => 3, 'description' => "Seluruh Unit (Unit Induk, Unit Pelaksana dan Sub Unit Pelaksana) telah melakukan pelaporan Unsafe Act, Unsafe Condition, Nearmiss dan Accident melalui Aplikasi Inspekta dan telah menetapkan User sesuai dengan ketentuan.\nUnit memonitor jumlah user active setiap bulannya , dengan target rata-rata 5%- 10% User Active dalam satu semester berdasarkan monitoring bulanannya\nmenyusun safety perfomance pyramid setiap bulan dan disampaikan ke seluruh pegawai", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 17, 'level' => 4, 'description' => "1. Tindak lanjut temuan Unit (Unit Induk, Unit Pelaksana dan Sub Unit Pelaksana) telah ditujukan kepada bidang terkait dan telah ditindaklanjuti sesuai dengan batas waktu yang telah ditentukan. dan dimonitor % temuan yang telah ditindaklanjuti terhadap total temuan setiap bulannya dan diinformasikan ke seluruh bidang bersama penyampaian safety perfomance pyramid setiap bulannya\n2. Unit memonitor jumlah user active setiap bulannya , dengan target rata-rata 10% User Active dalam satu semester berdasarkan monitoring bulanannya\n3. Reporting Culture Indeks mencapai 80%", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
            ['sub_criteria_id' => 17, 'level' => 5, 'description' => "Seluruh Unit (Unit Induk, Unit Pelaksana dan Sub Unit Pelaksana) memiliki Mapping Hazard dan Risk berdasarkan hasil temuan dan tindaklanjut serta analisa risiko dalam aplikasi inspekta.\nMemiliki safety perfomance pyramid dan monitoring tindak lanjut temuan dan disampaikan ke seluruh bidang progress penyelesaiannya >90% temuan terselesaikan.\nMemiliki OFI dan AFI yang disusun bersama K3L dan bidang terkait.\nReporting Culture Indeks mencapai 95%", 'evidence_requirement' => null, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}