@extends('layouts.atasan')

@section('title', 'Manajemen User')

@section('content')
<div class="space-y-6">
    <header class="border-b border-slate-200 pb-6"><p class="text-xs font-bold uppercase tracking-[0.2em] text-ocean">Administrasi Akses</p><h1 class="mt-2 font-display text-3xl font-bold text-ink">Manajemen User</h1><p class="mt-2 text-sm text-slate-600">Kelola akun, role, akses, dan password pengguna sistem.</p></header>

    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-display text-xl font-bold text-ink">Tambah Pengguna</h2><form action="{{ route('atasan.users.store') }}" method="POST" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-5">@csrf<input name="name" required placeholder="Nama lengkap" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input name="email" type="email" required placeholder="Email" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><select name="role" required class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="user">User</option><option value="admin">Verifikator Admin</option><option value="atasan">Atasan</option></select><input name="password" type="password" required minlength="6" placeholder="Password" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input name="password_confirmation" type="password" required minlength="6" placeholder="Ulangi password" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><button class="rounded-xl bg-ocean px-4 py-2.5 text-sm font-bold text-white transition hover:bg-cyan-800 md:col-span-2 lg:col-span-5 lg:justify-self-end">Tambah Pengguna</button></form></section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-[11px] uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Pengguna</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Ubah Data / Password</th><th class="px-5 py-3">Akses</th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($users as $user)
            <tr><td class="px-5 py-4"><form action="{{ route('atasan.users.update', $user) }}" method="POST" class="grid gap-2 sm:grid-cols-2">@csrf @method('PUT')<input name="name" value="{{ $user->name }}" required class="rounded-lg border border-slate-300 px-2 py-2 text-xs"><input name="email" type="email" value="{{ $user->email }}" required class="rounded-lg border border-slate-300 px-2 py-2 text-xs"><input name="password" type="password" minlength="6" placeholder="Password baru (opsional)" class="rounded-lg border border-slate-300 px-2 py-2 text-xs"><input name="password_confirmation" type="password" minlength="6" placeholder="Ulangi password" class="rounded-lg border border-slate-300 px-2 py-2 text-xs"><button class="rounded-lg bg-slate-800 px-3 py-2 text-xs font-bold text-white sm:col-span-2">Simpan perubahan</button></form></td><td class="px-5 py-4"><select form="role-form-{{ $user->id }}" name="role" class="rounded-lg border border-slate-300 px-2 py-2 text-xs"><option value="user" {{ $user->role === 'user' ? 'selected' : '' }}>User</option><option value="admin" {{ $user->role === 'admin' ? 'selected' : '' }}>Admin</option><option value="atasan" {{ $user->role === 'atasan' ? 'selected' : '' }}>Atasan</option></select></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $user->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600' }}">{{ $user->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="px-5 py-4 text-xs text-slate-500">Password diubah melalui form data pengguna.</td><td class="px-5 py-4"><form id="role-form-{{ $user->id }}" action="{{ route('atasan.users.update', $user) }}" method="POST">@csrf @method('PUT')<input type="hidden" name="name" value="{{ $user->name }}"><input type="hidden" name="email" value="{{ $user->email }}"><input type="hidden" name="password" value=""><input type="hidden" name="password_confirmation" value=""></form><form action="{{ route('atasan.users.toggle', $user) }}" method="POST" class="mt-2">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold text-slate-700">{{ $user->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></td></tr>
        @empty
            <tr><td colspan="5" class="px-5 py-12 text-center text-slate-400">Belum ada pengguna.</td></tr>
        @endforelse
    </tbody></table></div></section>
</div>
@endsection
